M48
; DRILL file {KiCad 9.0.0} date 2025-08-25T21:43:12+0300
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-08-25T21:43:12+03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.0
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0197
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0295
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.0472
%
G90
G05
T1
X5.5661Y-3.8367
T2
X5.5614Y-4.2232
T3
X4.8425Y-3.9488
X4.8425Y-4.126
M30
